version: '3.8'

services:
  db:
    image: postgres
    container_name: db-container-v3
    environment:
      POSTGRES_USER: vinayak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bajaj-db
    ports:
      - "5433:5432"
    volumes:
      - /Users/vinayakbora/Documents/docker-data:/var/lib/postgresql/data
  app:
    build: .
    image: jpa-app-v2
    container_name: jpa-app-cont
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bajaj-db
      SPRING_DATASOURCE_USERNAME: vinayak
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    restart: always
