apiVersion: apps/v1
kind: Deployment
metadata:
  name: bajajmall-app
  labels:
    app: bajajmall-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bajajmall-app
  template:
    metadata:
      labels:
        app: bajajmall-app
    spec:
      containers:
        - name: bajajmall-app-cont
          image: vinayakbora/bajajmall-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/bajajmall"
            - name: SPRING_DATASOURCE_USERNAME
              value: "vinayak"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: bajajmall-app-service
  labels:
    app: bajajmall-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: bajajmall-app
